config/routes.rb
Rails.application.routes.draw do
  devise_for :users
     devise_scope :user do
       get '/users/sign_out' => 'devise/sessions#destroy'
     end
  get 'persons/profile'
  resources :uslugis
  resources :icons
  get 'pages/usluga'
  get 'pages/oplata'
  get 'pages/park_texniki'
  get 'pages/nas'
  get 'pages/kontakt'
  get 'salon/index'
  get 'persons/profile', as: 'user_root'

  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root to: "salon#index", as: "salon"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/icon.rb
class Icon < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/uslugi.rb
class Uslugi < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  before_action :set_icon, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /icons or /icons.json
  def index
    @icons = Icon.all
  end

  # GET /icons/1 or /icons/1.json
  def show
  end

  # GET /icons/new
  def new
    @icon = Icon.new
  end

  # GET /icons/1/edit
  def edit
  end

  # POST /icons or /icons.json
  def create
    @icon = Icon.new(icon_params)

    respond_to do |format|
      if @icon.save
        format.html { redirect_to icon_url(@icon), notice: "Icon was successfully created." }
        format.json { render :show, status: :created, location: @icon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icons/1 or /icons/1.json
  def update
    respond_to do |format|
      if @icon.update(icon_params)
        format.html { redirect_to icon_url(@icon), notice: "Icon was successfully updated." }
        format.json { render :show, status: :ok, location: @icon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icons/1 or /icons/1.json
  def destroy
    @icon.destroy

    respond_to do |format|
      format.html { redirect_to icons_url, notice: "Icon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icon
      @icon = Icon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def icon_params
      params.require(:icon).permit(:title, :description, :image_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def usluga
    @uslugis = Uslugi.all
  end

  def nas
  end

  def kontakt
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url)
    end
end

app/controllers/salon_controller.rb
class SalonController < ApplicationController
  def index
    @products = Product.all
    @icons = Icon.all
  end
end

app/controllers/uslugis_controller.rb
class UslugisController < ApplicationController
  before_action :set_uslugi, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /uslugis or /uslugis.json
  def index
    @uslugis = Uslugi.all
  end

  # GET /uslugis/1 or /uslugis/1.json
  def show
  end

  # GET /uslugis/new
  def new
    @uslugi = Uslugi.new
  end

  # GET /uslugis/1/edit
  def edit
  end

  # POST /uslugis or /uslugis.json
  def create
    @uslugi = Uslugi.new(uslugi_params)

    respond_to do |format|
      if @uslugi.save
        format.html { redirect_to uslugi_url(@uslugi), notice: "Uslugi was successfully created." }
        format.json { render :show, status: :created, location: @uslugi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @uslugi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uslugis/1 or /uslugis/1.json
  def update
    respond_to do |format|
      if @uslugi.update(uslugi_params)
        format.html { redirect_to uslugi_url(@uslugi), notice: "Uslugi was successfully updated." }
        format.json { render :show, status: :ok, location: @uslugi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @uslugi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uslugis/1 or /uslugis/1.json
  def destroy
    @uslugi.destroy

    respond_to do |format|
      format.html { redirect_to uslugis_url, notice: "Uslugi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uslugi
      @uslugi = Uslugi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def uslugi_params
      params.require(:uslugi).permit(:title, :description, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/salon_helper.rb
module SalonHelper
end

app/helpers/uslugis_helper.rb
module UslugisHelper
end

app/views/icons/_form.html.erb
<%= form_with(model: icon) do |form| %>
  <% if icon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(icon.errors.count, "error") %> prohibited this icon from being saved:</h2>

      <ul>
        <% icon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/icons/_icon.html.erb
<div id="<%= dom_id icon %>">
  <p>
    <strong>Title:</strong>
    <%= icon.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= icon.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= icon.image_url %>
  </p>

</div>

app/views/icons/edit.html.erb
<h1>Editing icon</h1>

<%= render "form", icon: @icon %>

<br>

<div>
  <%= link_to "Show this icon", @icon %> |
  <%= link_to "Back to icons", icons_path %>
</div>

app/views/icons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Icons</h1>
<div id="user_nav">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>
  <%= link_to 'Edit', edit_user_registration_path %>
  <%= link_to 'Logout',destroy_user_session_path, method: :delete, data: {confirm: 'Вы уверены ?'} %>
<% else %>
  <%= link_to 'Sig in', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>
</div>
<div id="icons">
  <% @icons.each do |icon| %>
    <%= render icon %>
    <p>
      <%= link_to "Show this icon", icon %>
    </p>
  <% end %>
</div>

<%= link_to "New icon", new_icon_path %>

app/views/icons/new.html.erb
<h1>New icon</h1>

<%= render "form", icon: @icon %>

<br>

<div>
  <%= link_to "Back to icons", icons_path %>
</div>

app/views/icons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @icon %>

<div>
  <%= link_to "Edit this icon", edit_icon_path(@icon) %> |
  <%= link_to "Back to icons", icons_path %>

  <%= button_to "Destroy this icon", @icon, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Спец.техника, Наро-Фоминск, Селятино, Апрелевка </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="/assets/image">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="<%= controller.controller_name %>">
      
    <%= yield %>
  </body>
</html>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #42f599;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/salon/index"><%= image_tag("Logo", class: 'logo')%> <%= image_tag("buldoser", class: 'logo1' )%></a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav ">
      <li class="nav-item active">
        <a class="nav-link" href="/salon/index"  ><strong>Главная</strong> <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pages/usluga" ><strong>Услуги</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pages/oplata"><strong>Оплата</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pages/kontakt"><strong>Контакты</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pages/nas"><strong>О нас</strong></a>
      </li>
    </ul>
  </div>
</nav>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/kontakt.html.erb
<%= render "pages/navbar" %>
<div class="oplata">
  <h1>Наши контакты</h1>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="oplata1">
       <p>Наш офис находится по адресу:</p>
       <span> Москва, поселение Новофёдоровское,посёлок Рассудово, Железнодорожная улица, 4А    </span>
        <br>
        <br>
        <p>График работы:</p>
        <span>8:00-20:00 Пн-Сб</span>
        <br>
        <br>
        <p>Телефоны:</p>
        <span>+7 985 348 6666 || +7 985 850 23 63 </span>
        <br>
        <br>
        <p>Электронная почта:</p>
       <span>spectexniks.makaryan@ya.ru</span>
      </div>
    </div>
      <div class="col-md-6">
          <%= image_tag("karta.png", size: "600x400") %>
      </div>
    </div>
  </div>
</div>

app/views/pages/nas.html.erb
<%= render "pages/navbar" %>
<div class="oplata">
  <h1>О Нас</h1>
        <p>Наша компания предоставляет услуги по строительству дорог и аренде спецтехники в Москве и в Московкской области ц 2009 года. Мы обладаем широким опытом работы на рынке и станем надежным партнером для вашего бизнеса. Наша компания успешно выполнила большое количество крупных и мелких заказов и хорошо зарекомендовала себя среди клиентов.</p>
        <p>В большинстве проектов участвовала именно наша техника. Но бывали случаи, когда клиенту срочно требовалась помощь нашей компании в работе для соблюдения сроков. В таких ситуациях мы всегда шли навстречу — предоставляли необходимое количество рабочей силы и при этом не пытались получить сверхприбыль, мотивируя наценку срочностью заказа.</p>
        <p>Все машины находятся в исправном состоянии. Мы регулярно проводим их техосмотр в сертифицированных производителями сервисных центрах. Водители, которые сотрудничают с компанией, являются опытными специалистами в своей сфере. Они идеально управляемой доверенной техникой, знают обо всех её технических возможностях.</p>
  </div>

app/views/pages/oplata.html.erb
<%= render "pages/navbar" %>
<div class="oplata">
  <h1>Варианты оплаты</h1>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <%= image_tag('nal', class: 'oplata1' ) %>
        <h3>Наличный расчет </h3>
      </div>
      <div class="col-md-6">
        <%= image_tag('beznal', class: 'oplata1' ) %>
        <h3> Безналичный расчет</h3>
      </div>
    </div>
  </div>
  <br>
  <p>Мы работаем как с юридическими, так и с физическими лицами, и предлагаем различные варианты оплаты услуг.Вся документация (счета, акты, договоры) предоставляется оперативно.</p>
  <p>Открытость к сотрудничеству позволяет находить компромиссы в любых ситуациях. Мы готовы рассмотреть ваши предложения по оплате и обсудить индивидуальные условия.</p>
  <p>При заключении арендного соглашения вы не несете рисков, связанных с неожиданной поломкой дорогой техники. Арендовать специализированные машины можно в любой сезон. Помимо проката спецтехники, у нас можно заказать уборочные и земельные, грунтовые и дорожно-строительные работы.</p>
  </div>

app/views/pages/usluga.html.erb
<%= render "pages/navbar" %>
<div class="oplata">
  <h1>Наши услуги</h1>
  <div class="container">
    <div class="row">
      <% @uslugis.each do |uslugi| %>
        <div class="col-md-4">
            <p><%= image_tag(uslugi.image_url, class: 'image3')%></p>
            <div class="title2"><%= uslugi.description %></div>
          </div>
      <%	end  %>
  </div>
 </div>
</div>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/products/_form.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-6">
    <%= form_with(model: product) do |form| %>
      <% if product.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.text_field :title, class: 'form-control', placeholder: 'Наименование' %>
      </div>
      <br>
      <div class="form-group">
        <%= form.text_area :description, class: 'form-control', placeholder: 'Описание' %>
      </div>
      <br>
      <div class="form-group">
        <%= form.text_field :image_url, class: 'form-control', placeholder: 'Изображение' %>
      </div>
      <br>
      <div>
        <%= form.submit "Добавить", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= product.image_url %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Техника</h1>
<table>
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>
      <%= link_to 'Edit', edit_user_registration_path %>
      <%= link_to 'Logout',destroy_user_session_path, method: :delete, data: {confirm: 'Вы уверены ?'} %>
    <% else %>
      <%= link_to 'Sig in', new_user_registration_path %>
      <%= link_to 'Login', new_user_session_path %>
      <% end %>
      </div>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
        <%= image_tag(product.image_url, class: 'list_image') %>
      </td>
      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= product.description %></dd>
        </dl>
      </td>
      <td class="list_actions">
        <%= link_to 'Показать', product %><br/>
        <%= link_to 'Редактировать', edit_product_path(product) %><br/>
        <%= link_to 'Удалить', product, method: :delete,
                    data: { confirm: 'Вы уверены?' } %>
      </td>
    </tr>
  <% end %>
</table>
<br />
<%= link_to 'Новая техника', new_product_path %>

app/views/products/new.html.erb
<div class="title" >
  <h1>Новая машина</h1>
</div>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Назад", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Редактировать", edit_product_path(@product) %> |
  <%= link_to "Назад", products_path %>

  <%= button_to "Удалить", @product, method: :delete %>
</div>

app/views/salon/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="header">
      <h1> Вам нужна Спецтехника? Мы готовы предоставить 24/7</h1>
      <%= image_tag('telefon', class: 'tel' ) %>
      <%= image_tag('viber', class: 'tel' ) %>
      <%= image_tag('whatsapp', class: 'tel' ) %>
        <h4>+7 985 348 6666</h4>,
        <h4>+7 985 850 23 63</h4>
      <%= image_tag('email', class: 'tel1' ) %>
      <h4>spectexniks.makaryan@ya.ru/<h4>
    </div>
   <%= render "pages/navbar" %>
    <div class="line"></div>
    <div class="reklamma">
      <h4>АРЕНДА  СПЕЦТЕХНИКИ В МОСКВЕ И МОСКОВСКОЙ ОБЛАСТИ</h4>
      <p>Компания предлагает аренду спецтехники широкого назначения в Москве и Московской области для осуществления строительных, дорожно-ремонтных,демонтажных работ. Кроме того, выполняем дорожно-строительные, грунтовые, земляные и уборочные работы любого уровня сложности. Любая единица спецтехники стоит недешево, и поэтому сложно иметь в собственности все ее виды. Вот почему аренда является востребованной услугой в Москве и Московской области.</p>
    </div>
    <div class="container-fluid color">
      <div class="row">
        <div class="catalog"><h3>Каталог спецтехники</h3></div>
        <% @products.each do |product| %>
          <div class="col-md-3 page">
            <div class="bordert">
             <p><%= image_tag(product.image_url, class: 'image1')	%></p>
              <div class="title"><%= product.title %></div>
             </div>
          </div>
        <%	end  %>
      </div>
    </div>
    <div class="rek">
      <h3>Преимущество аренды спецтехники у Нас</h3>
      <div class="linia"></div>
    </div>
    <div class="container">
      <div class="row">
        <% @icons.each do |icon| %>
          <div class="col-md-3">
            <div class="border1">
            <p><%= image_tag(icon.image_url, class: 'image2')%></p>
              <div class="title1"><%= icon.description %></div>
            </div>
          </div>
        <%	end  %>
      </div>
    </div>

 <div class="footer">
          <p>©2023 Москва | Все права защищены | Политика обработки персональных данных</p>
      </div>
  </div>
</div>

app/views/uslugis/_form.html.erb
<%= form_with(model: uslugi) do |form| %>
  <% if uslugi.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(uslugi.errors.count, "error") %> prohibited this uslugi from being saved:</h2>

      <ul>
        <% uslugi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/uslugis/_uslugi.html.erb
<div id="<%= dom_id uslugi %>">
  <p>
    <strong>Title:</strong>
    <%= uslugi.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= uslugi.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= uslugi.image_url %>
  </p>

</div>

app/views/uslugis/edit.html.erb
<h1>Editing uslugi</h1>

<%= render "form", uslugi: @uslugi %>

<br>

<div>
  <%= link_to "Show this uslugi", @uslugi %> |
  <%= link_to "Back to uslugis", uslugis_path %>
</div>

app/views/uslugis/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Uslugis</h1>
div id="user_nav">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>
  <%= link_to 'Edit', edit_user_registration_path %>
  <%= link_to 'Logout',destroy_user_session_path, method: :delete, data: {confirm: 'Вы уверены ?'} %>
<% else %>
  <%= link_to 'Sig in', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>
</div>
<div id="uslugis">
  <% @uslugis.each do |uslugi| %>
    <%= render uslugi %>
    <p>
      <%= link_to "Show this uslugi", uslugi %>
    </p>
  <% end %>
</div>

<%= link_to "New uslugi", new_uslugi_path %>

app/views/uslugis/new.html.erb
<h1>New uslugi</h1>

<%= render "form", uslugi: @uslugi %>

<br>

<div>
  <%= link_to "Back to uslugis", uslugis_path %>
</div>

app/views/uslugis/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @uslugi %>

<div>
  <%= link_to "Edit this uslugi", edit_uslugi_path(@uslugi) %> |
  <%= link_to "Back to uslugis", uslugis_path %>

  <%= button_to "Destroy this uslugi", @uslugi, method: :delete %>
</div>